title: Weekly Billionaires
tagline: Researching a new billionaire every week.
description: Max Metcalf's research project of studying a new billionaire every week, documenting it, and publishing it to Twitter and as a newsletter.
url: https://www.weeklybillionaires.com
logo: /assets/images/maxmoji_thumbsup.png

twitter:
  username: weeklybillions
  card: summary

social:
  name: Weekly Billionaires
  links:
    - https://twitter.com/weeklybillions

permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
  - webpack.config.js
  - webpack

collections:
  authors:
    output: true
  billionaires:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "billionaires"
    values:
      layout: "billionaire"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "admin"
    values:
      sitemap: false
